# Generated by Django 6.0.5 on 2026-05-13 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Поле не должно содержать цифры.', regex='^[^\\d]*$')], verbose_name='Имя читателя'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Ошибка, телефон начинается с 7 и состоит из 11 цифр', regex='^7\\d{10}$')], verbose_name='Номер телефона'),
        ),
    ]
