# Generated by Django 6.0.5 on 2026-05-16 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_reader_name_alter_reader_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='reader',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Имя автора не должно содержать цифры.', regex='^[^\\d]*$')], verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Название книги не должно состоять из одних цифр.', regex='^[^\\d]*$')], verbose_name='Название книги'),
        ),
        migrations.DeleteModel(
            name='Reader',
        ),
    ]
